<?php
include "logic/connect_db.php"
?>

<!DOCTYPE html>
<html>
    <head>
      <? 
      require_once 'header.php'; 
      require_once 'logic/account.php'
      ?>
    </head>
    <body class="body-class">
        <main>
            <div class="background">
                <table class="account-table">
                    <tr>
                        <td style="text-align: center; width:450px; height:100px;">
                            <? echo "<h2>$nickname</h2>" ?>
                        </td>
                        <td style="text-align: center;">
                            <button style="width: 100px; margin-top: 0px;" type="submit" class="btn btn-dark">Выйти</a></button>
                        </td>
                    </tr>
                </table>
                <div class="folder-div">
                    <img src="картинки/folder.png" style="width:40px; margin: 15px;">
                    <p class="folder-title"><input class="form-control" type="text" placeholder="Новая папка"></p>
                    <img src="картинки/save.png" style="width:40px; margin: 15px; margin-left: auto; margin-right:15px;">
                </div>
                <?
                  while($row = $query->fetch_assoc()){
                    $folder_name = $row['folder_name'];
                    $privacy = $row['privacy'];
                    ?>
                    <div class="folder-div">
                      <img src="картинки/folder.png" style="width:40px; margin: 15px;">
                      <p class="folder-title"><? echo "$folder_name"; ?></p>
                      <div class="form-check" style="margin: 15px; margin-left: auto;">
                        <input class="form-check-input" type="checkbox" id="flexCheckDefault" <? if($privacy) echo "checked"; ?>>
                        <label class="form-check-label" for="flexCheckDefault" >
                          Приватный
                        </label>
                      </div>
                      <img src="картинки/delete.png" style="width:40px; margin: 15px; margin-left: auto;">
                    </div>
                    <?
                  }
                ?>
            </div>
        </main>
        <footer>

        </footer>
    </body>
</html>