<?php
include "logic/connect_db.php"
?>

<!DOCTYPE html>
<html>
    <head>
      <? 
      require_once 'header.php'; 
      require_once 'logic/account.php'
      ?>
    </head>
    <body class="body-class">
        <main>
            <div class="background">
                <table class="account-table">
                    <tr>
                        <td style="text-align: center; width:450px; height:100px;">
                            <? echo "<h2>$nickname</h2>" ?>
                        </td>
                        <td style="text-align: center;">
                            <a href="logic/exit.php"><button style="width: 100px; margin-top: 0px;" type="submit" class="btn btn-dark">Выйти</button></a>
                            <? 
                              if ($_SESSION['isAdmin'] == 1) 
                              echo "<a href='logic/insert.php'><button style='width: 180px; margin-top: 0px;' type='submit' class='btn btn-outline-primary'>Добавить фильм</button></a>"
                            ?>
                        </td>
                    </tr>
                </table>
                <form name="addfolder" action="logic/addfolder.php" method="POST">
                  <div class="folder-div">
                      <img src="картинки/folder.png" style="width:40px; margin: 15px;">
                      <p class="folder-title"><input class="form-control" type="text" name="folder_name" placeholder="Новая подборка"></p>
                      <div class="form-check" style="margin-top: 20px; margin-right: 5px; margin-left: auto;" name="privacy">
                        <input class="form-check-input" type="checkbox" name="privacy">
                        <label class="form-check-label">
                          Приватная
                        </label>
                      </div>
                      <a href='logic/addfolder.php' style="margin: 15px; margin-left: auto; margin-top: 10px;" class="link"><button type="submit" class="btn btn-outline-info"><img src="картинки/save.png" style="width:40px;"></button></a>
                  </div>
                </form>
                <?
                  while($row = $query->fetch_assoc()){
                    $folder_name = $row['folder_name'];
                    $privacy = $row['privacy'];
                    $idcollection = $row['idfolders'];
                    ?>
                    <a href='collection.phtml?idcollection=<?echo "$idcollection";?>' class="link">
                    <div class="folder-div">
                      <img src="картинки/folder.png" style="width:40px; margin: 15px;" >
                      <p class="folder-title"><? echo "$folder_name"; ?></p>
                      <div class="form-check" style="margin: 20px; margin-left: auto;">
                        <input class="form-check-input" type="checkbox" id="flexCheckDisabled" <? if($privacy) echo "checked"; ?> disabled>
                        <label class="form-check-label" for="flexCheckDisabled" >
                          Приватная
                        </label>
                      </div>
                      <form method="POST" action="logic/delfolder.php">
                        <div>
                          <input type="hidden" name="idcollection" value="<? echo "$idcollection"; ?>">
                          <button type="submit" class="btn btn-outline-danger" style="margin-left: 75px; margin-top: 10px; margin-right: 15px;"><img src="картинки/delete.png" style="width:40px;"></button>
                        </div>
                      </form>
                    </div>
                    </a>
                    <?
                  }
                ?>
            </div>
        </main>
        <footer>

        </footer>
    </body>
</html>