<?php
include "logic/connect_db.php";
?>

<!DOCTYPE html>
<html>
    <head>
        <? 
          require_once 'header.php';  
          require_once 'logic/collection.php'; 
        ?>
    </head>
    <body class="body-class" style="background-color: #f1d36f">
        <main>
            <div class="background">
              <h2 class="folder-h2"><b>
              <? 
              if (($_SESSION['id'] != $user_iduser) && ($privacy == 1)) 
                echo "GET OUT OF MY SWAMP</b></h2>"; 
              else {
                $idcollection = $_GET['idcollection'];
                
                echo "<a href='account.phtml'><img src='картинки/folder.png' style='width:30px; margin-right: 15px; padding-bottom: 5px;'></a>$folder_name </b>";
                if ($_SESSION['id'] == $user_iduser) 
                    echo"
                      <button type='button' class='btn btn-outline-info' style='width:60px;' data-bs-toggle='modal' data-bs-target='#edit'><img src='картинки/pen.png' style='width:20px; padding-bottom: 5px;'></button>
                      <button type='button' class='btn btn-outline-danger' style='width:60px; height:40px;' data-bs-toggle='modal' data-bs-target='#delete'><img src='картинки/delete.png' style='width:30px;'></button>
                      ";
                  echo"
                  </h2>
                <div style='clear: both'>
                  <h4 class='folder-h2' style='display: inline-block'><b>Описание: </b></h4>
                  <h6 style='display: inline-block'>$description_f</h6>
                </div>
                ";
                if ($folders_has_media->num_rows == 0) echo "<h4 class='folder-h2' style='display: inline-block'><b>Эта подборка пуста</b></h4>";

                while($row_f = $folders_has_media->fetch_assoc())
                {
                  $idmedia = $row_f['media_idmedia'];
                  $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
                  $folder_media = $con->query("SELECT * FROM media WHERE idmedia = '$idmedia'");
                  $gcheck=$item_genres->num_rows;
                  while($row_m = $folder_media->fetch_assoc()){
                    $show_img = base64_encode($row_m['image_cover']);
                    $title = $row_m['title'];
                    $rating = $row_m['rating'];
                    $release = date("Y",strtotime($row_m['release']));
                    $cat = $row_m['category_idcategory'];

                    ?>
                    <a href="media.phtml?idmedia=<?php echo $idmedia;?>" class="link">
                      <div class="one-item-folder">
                        <table>
                          <tr>
                            <td>
                              <img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt="">
                            </td>
                            <td>
                              <?
                              echo"
                              <p><b>$title /$release/</b><a href='category.php?idcategory=$cat'; class='link'><em style='color: #6495ED; margin-left: 15px;'>$category</em></p></a>
                              <p><b>Жанры: </b>";
                              while($row = $item_genres->fetch_assoc()){
                                $idgenre = $row['genres_idgenre'];
                                $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                                while($row = $genre_tmp->fetch_assoc()){
                                  $genre = $row['name'];
                                  if ($gcheck > 1) 
                                  {
                                    echo "$genre, ";
                                    $gcheck--;
                                  }
                                  else echo "$genre";
                                }
                              }
                              echo"</p>
                              <p><b>Рейтинг: </b>$rating</p>";
                              
                              if ($_SESSION['id'] == $user_iduser)
                              echo"
                              <form method='POST' action='logic/delfoldermedia.php'>
                                <div>
                                  <input type='hidden' name='idmedia' value='$idmedia'>
                                  <input type='hidden' name='idcollection' value='$idcollection'>
                                  <p><a class='highlighted-link' href='logic/delfoldermedia.php'><button type='submit' class='btn btn-outline-danger'>Удалить из подборки</button></a></p>
                                </div>
                              </form>
                              ";
                              ?>
                            </td>
                          </tr>
                        </table>
                      </div>
                    </a>
                    <?
                  }
                }
              }
              ?>
              <div class="modal fade" id="edit" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <form name="editcollection" action="logic/editcollection.php" method="POST">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Внести изменения в подборку</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                      </div>
                      <div class="modal-body">
                          <div class="input-group" name="new_name">
                            <div class="input-group-prepend">
                              <span class="input-group-text" id="inputGroup">Название</span>
                            </div>
                            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="не >40 символов" value="<?echo $folder_name;?>" name="new_name">
                          </div>
                          <div>
                            <label>Описание</label>
                            <textarea class="form-control" rows="3" value="<?echo $description_f;?>" name="new_description" placeholder="не >400 символов"></textarea>
                          </div>
                          <div class="form-check" style="margin: 20px; margin-left: auto;" name="newprivacy">
                            <input class="form-check-input" type="checkbox" id="flexCheck" <? if($privacy) echo "checked"; ?> name="new_privacy">
                            <label class="form-check-label" for="flexCheck">Сделать приватной</label>
                          </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                      </div>
                      <input type='hidden' name='idcollection' value=<?echo $idcollection;?>>
                    </div>
                  </div>
                </form>
              </div>
            </div>
        </main>
    </body>
</html>