<?php
include "logic/connect_db.php";
?>

<!DOCTYPE html>
<html>
    <head>
      <?php 
      require_once 'header.php'; 
      ?>
    </head>
    <main>
          <table class="table-for-carousel-and-category">
            <tr>
              <td rowspan="2">
                <div class="carousel-box">
                  <?php 
                    require_once 'index_images.php'; 
                  ?>
                </div>
              </td>
              <td class="cell-visible">
                <a href="category.php?idcategory=1" class="link"><h1><b>Фильмы</b></h1>
                <div class="carousel-category">
                  <div id="carouselExample" class="carousel slide">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="картинки/картинка7.jpg" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="картинки/alice.jpg" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="картинки/картинка9.jpg" class="d-block w-100" alt="...">
                      </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                </div>
                </a>
              </td>
              <tr>
                <td class="cell-visible">
                  <a href="category.php?idcategory=3" class="link"><h1><b>Аниме</b></h1>
                  <div class="carousel-category">
                    <div id="carouselExample1" class="carousel slide">
                      <div class="carousel-inner">
                        <div class="carousel-item active">
                          <img src="картинки/1картинка.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                          <img src="картинки/картинка5.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                          <img src="картинки/картинка6.jpg" class="d-block w-100" alt="...">
                        </div>
                      </div>
                  </a>
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample1" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample1" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    </div>
                  </div>
                </td>
              </tr>
          </table>
        </main>
        <footer>

        </footer>
    </body>
</html>