<?php
include "logic/connect_db.php"
?>

<!DOCTYPE html>
<html>
    <head>
      <?php require_once 'header.php'; ?>
    </head>
    <main style="background-color: #252850;">
        <div class="background">
            <table class="movie-table">
                <?php
                    $query = $con->query("SELECT * FROM media WHERE idmedia=".$_GET['idmedia']."");
                    $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia=".$_GET['idmedia']."");
                    $img_screenshots = $con->query("SELECT * FROM images WHERE media_idmedia=".$_GET['idmedia']."");
                    $gcheck=$item_genres->num_rows;
                    $icheck=$img_screenshots->num_rows;
                    while($row = $query->fetch_assoc()){
                        $show_img = base64_encode($row['image_cover']);
                        $title = $row['title'];
                        $rating = $row['rating'];
                        $release = date("Y",strtotime($row['release']));
                        $description = $row['description'];
                        $trailer = $row['trailer'];
                        $embeded_trailer = str_replace("watch?v=", "embed/", $trailer);
                    }
                ?>
                <tr>
                    <td rowspan="3" class="poster-cell"><img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt=""></td>
                    <td class="inscription1"><h2><b><? echo $title?></b></h2></td>
                </tr>
                <tr>
                    <td class="inscription2">
                        <h4><p><b><? echo $release?></b></p></h4>
                        <p><b>Жанры: </b>
                        <? 
                        while($row = $item_genres->fetch_assoc()){
                            $idgenre = $row['genres_idgenre'];
                            $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                            while($row = $genre_tmp->fetch_assoc()){
                                $genre = $row['name'];
                                if ($gcheck > 1) 
                                {
                                    echo "$genre, ";
                                    $gcheck--;
                                }
                                else echo "$genre";
                            }
                        }?></p>
                        <p><b>Рейтинг: </b><? echo $rating?></p>
                    </td>
                </tr>
                <tr>
                    <td class="inscription3">
                        <button style="margin-top: 15px; margin-bottom: 10px; width: 190px;" type="submit" class="btn btn-dark">Добавить к себе</button>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <h3><b>Описание</b></h3>
                        <p style="margin-bottom: 0px;"><? echo $description?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <? 
                            if ($icheck != 0) 
                            {   
                                echo "<h3><b>Изображения</b></h3>";
                                require_once "screenshots.php";
                            }
                        ?>
                        
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <h3><b>Трейлер</b></h3>
                        <iframe width="800" height="450" style="margin-bottom: 50px;" src="<? echo $embeded_trailer;?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    </td>
                </tr>

            </table>
        </div>
    </main>
    <footer>

    </footer>
    </body>
</html>