<!DOCTYPE html>
<html>
    <head>
      <?php require_once 'header.php'; ?>
    </head>
    <main style="background-color: #252850;">
        <div class="background">
            <table class="movie-table">
                <tr>
                    <td rowspan="3" class="poster-cell"><img class="poster" src="картинки/картинка2.jpg"></td>
                    <td class="inscription1"><h2><b>Богемская рапсодия</b></h2></td>
                </tr>
                <tr>
                    <td class="inscription2">
                        <p><b>Год выхода: </b>2018</p>
                        <p><b>Жанры: </b>Музыкальный фильм, драма</p>
                        <p><b>Рейтинг: </b>8.1</p>
                        <b>Описание:</b>
                        <p style="margin-bottom: 0px;">Чествование группы Queen, их музыки и их выдающегося вокалиста Фредди Меркьюри, который бросил вызов стереотипам и победил условности, чтобы стать одним из самых любимых артистов на планете.</p>
                    </td>
                </tr>
                <tr>
                    <td class="inscription3">
                        <button style="margin-top: 15px; width: 190px;" type="submit" class="btn btn-dark">Добавить к себе</button>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <h3><b>Обзор</b></h3>
                        <p style="margin-bottom: 0px;">Фредди Меркьюри – это легенда. Вы можете не быть фанатом группы «Queen», но их песни вам хорошо известны. Фредди был яркой, талантливой личностью и умер 30 лет назад, но его музыка и песни до сих пор живы и популярны. Их перепевают, они звучат на радиостанциях и в современном кино, и у группы до сих пор множество фанатов и поклонников по всему миру. Фильм «Богемская рапсодия» снятый о группе «Queen», рассказывает историю популярного коллектива с момента их образования и до важного благотворительного концерта на стадионе Уэмбли, прошедшего за несколько лет до кончины солиста Фредди Меркьюри.</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="movie-table"><iframe width="800" height="450" style="margin-left: 30px; margin-top: 20px;" src="https://www.youtube.com/embed/e9sz7ZbCmKk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                </tr>

            </table>
        </div>
    </main>
    <footer>

    </footer>
    </body>
</html>