<?php
include "logic/connect_db.php"
?>

<!DOCTYPE html>
<html>
    <head>
        <?php require_once 'header.php'; ?>
    </head>
    <main style="background-color: #252850;">
        <div class="background">
            <table class="movie-table">
                <?php
                    $idmedia = $_GET['idmedia'];
                    $query = $con->query("SELECT * FROM media WHERE idmedia=".$_GET['idmedia']."");
                    $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia=".$_GET['idmedia']."");
                    $img_screenshots = $con->query("SELECT * FROM images WHERE media_idmedia=".$_GET['idmedia']."");
                    $gcheck=$item_genres->num_rows;
                    $icheck=$img_screenshots->num_rows;
                    while($row = $query->fetch_assoc()){
                        $show_img = base64_encode($row['image_cover']);
                        $title = $row['title'];
                        $rating = $row['rating'];
                        $release = date("Y",strtotime($row['release']));
                        $description = $row['description'];
                        $trailer = $row['trailer'];
                        $embeded_trailer = str_replace("watch?v=", "embed/", $trailer);
                    }
                ?>
                <tr>
                    <td rowspan="3" class="poster-cell"><img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt=""></td>
                    <td class="inscription1"><h2><b><? echo $title?></b></h2></td>
                </tr>
                <tr>
                    <td class="inscription2">
                        <h4><p><b><? echo $release?></b></p></h4>
                        <p><b>Жанры: </b>
                        <? 
                        while($row = $item_genres->fetch_assoc()){
                            $idgenre = $row['genres_idgenre'];
                            $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                            while($row = $genre_tmp->fetch_assoc()){
                                $genre = $row['name'];
                                if ($gcheck > 1) 
                                {
                                    echo "$genre, ";
                                    $gcheck--;
                                }
                                else echo "$genre";
                            }
                        }?></p>
                        <p><b>Рейтинг: </b><? echo $rating?></p>
                    </td>
                </tr>
                <tr>
                    <td class="inscription3">
                        <button id="show" style="margin-top: 15px; margin-bottom: 10px; width: 190px;" type="submit" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#addModal">Добавить к себе</button>
                        <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <form name="myform"  action='logic/addmedia.php' method="POST">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="ModalLabel"><? if ($_SESSION['id']==NULL) echo "Упс"; else echo "Добавить в свою подборку"; ?></h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                                        </div>
                                        <div class="modal-body">
                                            <? 
                                            if ($_SESSION['id']==NULL) 
                                            echo "Сначала <a href='login.phtml' class='tooltip-test' title='Вход в личный кабинет'>войдите</a> или <a href='register.phtml' class='tooltip-test' title='Регистрация'>зарегистрируйтесь</a>"; 
                                            else {
                                                echo "
                                                    <input type='hidden' name='idmedia' value='$idmedia'>
                                                    <select class='form-select' name='to_folder'>
                                                        <option selected value='new'>Новая подборка</option>
                                                ";
                                                $folders = $con->query("SELECT * FROM folders WHERE user_iduser=".$_SESSION['id']."");
                                                while($row = $folders->fetch_assoc()){
                                                    $id_folder = $row['idfolders'];
                                                    $folder_name = $row['folder_name'];
                                                    $media_in_folder = $con->query("SELECT * FROM folders_has_media WHERE folders_idfolders='$id_folder'");
                                                    while($row_media = $media_in_folder->fetch_assoc()){
                                                        $media_idmedia = $row_media['media_idmedia'];
                                                        if ($media_idmedia == $_GET['idmedia']) $has_media = "true";
                                                    }
                                                    if ($has_media == "true")
                                                    {
                                                        echo"<option value='$id_folder' disabled style='background-color: #bcbcbc;'>$folder_name (уже в данной подборке)</option>";
                                                        $has_media = "false";
                                                    }
                                                    else
                                                        echo"<option name='to_folder' value='$id_folder'>$folder_name</option>";
                                                }
                                                echo"</select>";
                                            }
                                            ?>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                            <?if ($_SESSION['id'] != NULL) echo "<button type='submit' class='btn btn-primary'>Сохранить</button>";?>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <h3><b>Описание</b></h3>
                        <p style="margin-bottom: 0px;"><? echo $description?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <? 
                            if ($icheck != 0) 
                            {   
                                echo "<h3><b>Изображения</b></h3>";
                                require_once "screenshots.php";
                            }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="overview-cell">
                        <h3><b>Трейлер</b></h3>
                        <iframe width="800" height="450" style="margin-bottom: 50px;" src="<? echo $embeded_trailer;?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    </td>
                </tr>

            </table>
        </div>
    </main>
    </body>
</html>