<?php
include "logic/connect_db.php";
?>

<!DOCTYPE html>
<html> 
<head>
  <? require_once 'header.php'; ?>
</head>
    <main style="background-color: #1f9fff;">
      <div class="background">
        <?
            require_once "logic/search.php";
            $sorting = $_GET['sort'];
            $showing = $_GET['show'];
        ?>
        <form class="d-flex" action="search.phtml" role="search" method="GET" style="padding: 20px; background-color: cyan;">
            <div>
                <input class="form-control me-2" type="search" placeholder="Название фильма" name="search" value=<?echo $_GET['search'];?>>
                <button class="btn btn-outline-primary" type="submit">Найти</button>
            </div>
            <div class="form-group" style="padding-left: 20px; margin-bottom: 20px;">
                <label class="col-lg-2">Сортировать:</label>
                <div>
                    <input type="radio" name="sort" value="rating" <? if ($sorting == 'rating') echo"checked";?>>По рейтингу
                    <input type="radio" name="sort" value="date" <? if ($sorting == 'date') echo"checked";?>>По дате выхода
                    <input type="radio" name="sort" value="alphabet" <? if ($sorting == 'alphabet') echo"checked";?>>По алфавиту
                </div>
            </div>
            <div class="form-group" style="padding-left: 20px; margin-bottom: 20px;">
                <label class="col-lg-2">Сортировать:</label>
                <div>
                    <select name="show">
                        <option value="all">Показать все результаты</option>
                        <option value="films">Только фильмы</option>
                        <option value="series">Только сериалы</option>
                        <option value="anime">Только аниме</option>
                        <option value="collection">Только подборки</option>
                    </select>
                </div>
            </div>
        </form>
        <div style="padding-left: 20px; margin-bottom: 20px;">
            <h3><b>
                <? 
                if (empty($_GET['search'])) 
                    echo "Пожалуйста, введите поисковый запрос <img src='картинки/not_found.png' style='margin-left: 5px; width:40px;'>"; 
                else {
                    echo"Результаты поиска: ";
                    echo $_GET['search']; 
                }
                ?>
            </b></h3>
            <? 
                $checking = $search_media->num_rows;
                if (!empty($_GET['search']))
                if (($checking == 0)){
                    if ($_GET['show'] != "collection")
                    echo"
                      <div style='padding-left: 5%;'>
                      <img src='картинки/not_found.png' style='width:40px;'>
                      <label><h5>По запросу ничего не найдено</h5></label>
                      </div>
                      ";
                    }
                    else{
                        for ($i = 1; $i <=3; $i++)
                        {
                            while($row = $search_media->fetch_assoc()){
                                $idmedia = $row['idmedia'];
                                $show_img = base64_encode($row['image_cover']);
                                $title = $row['title'];
                                $rating = $row['rating'];
                                $release = date("Y",strtotime($row['release']));
                                $cat = $row['category_idcategory'];
                                $description = $row['description'];

                                switch ($cat){
                                    case(1):
                                        $category="Фильм";
                                        break;
                                    case(2):
                                        $category="Сериал";
                                        break;
                                    case(3):
                                        $category="Аниме";
                                        break;
                                }
                                

                                $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
                                $gcheck=$item_genres->num_rows;
                                ?>
                                
                                <a href="media.phtml?idmedia=<?php echo $idmedia;?>" class="link">
                                <div class="one-item">
                                    <table>
                                        <tr>
                                            <td>
                                                <img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt="">
                                            </td>
                                        <td>
                                            <?
                                            echo"
                                            <p><b>$title /$release/</b><a href='category.php?idcategory=$cat'; class='link'><em style='color: #6495ED; margin-left: 15px;'>$category</em></p></a>
                                            <p><b>Жанры: </b>";
                                            while($row = $item_genres->fetch_assoc()){
                                                $idgenre = $row['genres_idgenre'];
                                                $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                                                while($row = $genre_tmp->fetch_assoc()){
                                                    $genre = $row['name'];
                                                    if ($gcheck > 1) 
                                                    {
                                                        echo "$genre, ";
                                                        $gcheck--;
                                                    }
                                                    else echo "$genre";
                                                }
                                            }
                                            echo"</p>
                                            <p><b>Рейтинг: </b>$rating</p>
                                            <b>Описание:</b>
                                            <p style='overflow: auto; height: 80px; padding-right: 20px;'>$description</p>
                                            ";
                                            ?>
                                        </td>
                                        </tr>
                                    </table>
                                </div></a>
                            <?
                            }
                        }
                    }
            ?>


            <?
            if (!empty($_GET['search'])) {
                if (($_GET['show'] == "collection") || ($_GET['show'] == "all") || (empty($_GET['show']))){
                    ?> <h2><b>Подборки</b></h2> <?
                    if ($search_folder->num_rows == 0){
                        echo"
                        <div style='padding-left: 5%; padding-bottom: 10%;'>
                            <img src='картинки/not_found.png' style='width:40px;'>
                            <label><h5>По запросу ничего не найдено</h5></label>
                        </div>
                        ";
                    }
                    else{
                        for ($i = 1; $i <=3; $i++)
                        {
                            while($row = $search_folder->fetch_assoc()){
                                $idfolders  = $row['idfolders'];
                                $folder_name = $row['folder_name'];
                                $privacy = $row['privacy'];
                                $descriptionf = $row['description'];

                                if ($privacy != 1){
                                ?>
                                <a href="collection.phtml?idcollection=<? echo"$idfolders" ?>" class="link"><div class="one-item">
                                <div class="folder-div">
                                    <img src="картинки/folder.png" style="width:40px; margin: 15px;">
                                    <p class="folder-title"><? echo"$folder_name" ?></p>
                                    <p style='overflow: hidden; text-overflow: ellipsis; height: 55px; width: 300px; padding-right: 20px;'><b>Описание:</b><br><? echo "$descriptionf" ?></p>
                                </div></a>
                                
                                <?
                                }
                            }
                        }
                    }
                }
            }

            ?>
        </div>
    </main>
</html>