<?php
include "logic/connect_db.php";
?>

<!DOCTYPE html>
<html> 
<head>
  <? require_once 'header.php'; ?>
</head>
    <main style="background-color: #1f9fff;">
      <div class="background">
        <?
        require_once "logic/search.php"
        ?>
        <div style="padding-left: 20px; padding-top: 20px; margin-bottom: 20px;">
          <h3><b>Ищем: <?echo "$search_item";?></b></h3>
        </div>

        <?
        /*$check_genre = $con->query("SELECT * FROM genres WHERE idgenre='$search_item'");
        $check_g = $check_genre->num_rows;
        if (check_g != 0){
          while($row = $query->fetch_assoc()){
            $show_g = $row['genres'];
            echo"<div style='padding-left: 20px; padding-top: 20px; margin-bottom: 20px;'>
              <h3>Возможно вы искали жанр ЗАКЛЮЧИТЬ ЕГО В ССЫЛКУ</h3>
            </div>";
          }
          
        }*/
        
        if (isset($show_film)){
          $que = $con->query($search_media);
          $checking = $que->num_rows;
          echo "<h2><b>Фильмы</b></h2>";
          if ($checking == 0){
          echo"
            <div style='padding-left: 5%;'>
            <img src='картинки/not_found.png' style='width:40px;'>
            <label><h5>По запросу ничего не найдено</h5></label>
            </div>
            ";
          }
          else{
            while($row = $query->fetch_assoc()){
              $idmedia = $row['idmedia'];
              $show_img = base64_encode($row['image_cover']);
              $title = $row['title'];
              $rating = $row['rating'];
              $release = date("Y",strtotime($row['release']));
              $description = $row['description'];

              $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
              $gcheck=$item_genres->num_rows;
              ?>
              <div class="one-item">
              <a href="media.phtml?idmedia=<?php echo $idmedia;?>" class="link">
              <table>
                  <tr>
                  <td>
                      <img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt="">
                  </td>
                  <td>
                <?
                echo"
                <p><b>$title /$release/</b></p>
                <p><b>Жанры: </b>";
                while($row = $item_genres->fetch_assoc()){
                    $idgenre = $row['genres_idgenre'];
                    $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                    while($row = $genre_tmp->fetch_assoc()){
                        $genre = $row['name'];
                        if ($gcheck > 1) 
                        {
                            echo "$genre, ";
                            $gcheck--;
                        }
                        else echo "$genre";
                    }
                }
                echo"</p>
                <p><b>Рейтинг: </b>$rating</p>
                <b>Описание:</b>
                <p style='overflow: auto; height: 80px; padding-right: 20px;'>$description</p>
                ";
                ?>
              </td>
                  </tr>
              </table>
              </div></a>
            <?
            }
          }
        }

        if (isset($show_series)){
          $query = $con->query($search_media);
          $checking = $query->num_rows;
          echo "<h2><b>Фильмы</b></h2>";
          if ($checking == 0){
          echo"
            <div style='padding-left: 5%;'>
            <img src='картинки/not_found.png' style='width:40px;'>
            <label><h5>По запросу ничего не найдено</h5></label>
            </div>
            ";
          }
          else{
            while($row = $query->fetch_assoc()){
              $idmedia = $row['idmedia'];
              $show_img = base64_encode($row['image_cover']);
              $title = $row['title'];
              $rating = $row['rating'];
              $release = date("Y",strtotime($row['release']));
              $description = $row['description'];

              $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
              $gcheck=$item_genres->num_rows;
              ?>
              <div class="one-item">
              <a href="media.phtml?idmedia=<?php echo $idmedia;?>" class="link">
              <table>
                  <tr>
                  <td>
                      <img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt="">
                  </td>
                  <td>
                <?
                echo"
                <p><b>$title /$release/</b></p>
                <p><b>Жанры: </b>";
                while($row = $item_genres->fetch_assoc()){
                    $idgenre = $row['genres_idgenre'];
                    $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                    while($row = $genre_tmp->fetch_assoc()){
                        $genre = $row['name'];
                        if ($gcheck > 1) 
                        {
                            echo "$genre, ";
                            $gcheck--;
                        }
                        else echo "$genre";
                    }
                }
                echo"</p>
                <p><b>Рейтинг: </b>$rating</p>
                <b>Описание:</b>
                <p style='overflow: auto; height: 80px; padding-right: 20px;'>$description</p>
                ";
                ?>
              </td>
                  </tr>
              </table>
              </div></a>
            <?
            }
          }
        }

        if (isset($show_anime)){
          $query = $con->query($search_media);
          $checking = $query->num_rows;
          echo "<h2><b>Фильмы</b></h2>";
          if ($checking == 0){
          echo"
            <div style='padding-left: 5%;'>
            <img src='картинки/not_found.png' style='width:40px;'>
            <label><h5>По запросу ничего не найдено</h5></label>
            </div>
            ";
          }
          else{
            while($row = $query->fetch_assoc()){
              $idmedia = $row['idmedia'];
              $show_img = base64_encode($row['image_cover']);
              $title = $row['title'];
              $rating = $row['rating'];
              $release = date("Y",strtotime($row['release']));
              $description = $row['description'];

              $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
              $gcheck=$item_genres->num_rows;
              ?>
              <div class="one-item">
              <a href="media.phtml?idmedia=<?php echo $idmedia;?>" class="link">
              <table>
                  <tr>
                  <td>
                      <img class="poster" src="data:image/jpeg;base64, <?=$show_img?>" alt="">
                  </td>
                  <td>
                <?
                echo"
                <p><b>$title /$release/</b></p>
                <p><b>Жанры: </b>";
                while($row = $item_genres->fetch_assoc()){
                    $idgenre = $row['genres_idgenre'];
                    $genre_tmp = $con->query("SELECT * FROM genres WHERE idgenre='$idgenre'");
                    while($row = $genre_tmp->fetch_assoc()){
                        $genre = $row['name'];
                        if ($gcheck > 1) 
                        {
                            echo "$genre, ";
                            $gcheck--;
                        }
                        else echo "$genre";
                    }
                }
                echo"</p>
                <p><b>Рейтинг: </b>$rating</p>
                <b>Описание:</b>
                <p style='overflow: auto; height: 80px; padding-right: 20px;'>$description</p>
                ";
                ?>
              </td>
                  </tr>
              </table>
              </div></a>
            <?
            }
          }
        }
        
        //show_folders
        ?>
          <h2><b>Папки</b></h2>
          <div class="folder-div">
            <img src="картинки/folder.png" style="width:40px; margin: 15px;">
            <p class="folder-title">Название</p>
          </div>
        </div>
      </div>
    </main>
</html>





<? //тут просто то, что делал, не пропадать же добру  ?>


<div class="dropdown-content" style="padding: 10%; width: 360px;">
                <table>
                  <tr>
                        <td>
                          <div>Сортировать по</div>
                          <div class="form-check">
                              <input class="form-check-input" type="radio" id="ratig" name="drone" value="rating">
                              <label class="form-check-label" for="rating">Рейтингу</label>
                            </div>
                          <div>
                              <input class="form-check-input" type="radio" id="release" name="drone" value="release">
                              <label class="form-check-label" for="release">Дате</label>
                            </div>
                            <div>
                              <input class="form-check-input" type="radio" id="title" name="drone" value="title">
                              <label class="form-check-label" for="title">Имени</label>
                            </div>
                        </td>
                        <td style="padding-left: 60px;">
                          <div>Показать:</div>
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="show[]" value="show_film" id="show_film">
                              <label class="form-check-label" for="film">Фильмы</label>
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="show[]" value="show_series" id="show_series">
                                <label class="form-check-label" for="series">Сериалы</label>
                            </div>
                            
                            <div>
                                <input class="form-check-input" type="checkbox" name="show[]" value="show_anime" id="show_anime">
                                <label class="form-check-label" for="anime">Аниме</label>
                            </div class="form-check">
                            
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="show[]" value="show_folder" id="show_folder">
                                <label  class="form-check-label" for="boxes">Подборки</label>
                            </div>
                        </td>
                    </tr>
                </table>
              </div>