<?php
include "logic/connect_db.php";
?>

<!DOCTYPE html>
<html> 
<head>
  <? require_once 'header.php'; ?>
</head>
    <main style="background-color: #1f9fff;">
      <div class="background">
        <div style="padding-left: 20px; padding-top: 20px; margin-bottom: 20px;">
          <h3><b>Ищем:</b></h3>
        </div>
        <?
        require_once "logic/search.php"
        
        if (isset($show_genre)){
          echo"
          <div style='padding-left: 20px; padding-top: 20px; margin-bottom: 10px;'>
          <h2><b>Жанр в категориях:</b></h2>
          ";

          for ($i = 1; $i <= 3; $i++) {
            echo"
            <div style='padding-left: 20px; padding-top: 20px; margin-bottom: 10px;'>
            <h2><b>Жанры</b></h2>
            ";
              $query = $con->query("SELECT * FROM media WHERE category_idcategory='$i' IN ('$search_genre')");
              $checking = $query->num_rows;
              if ($checking == 0){
                echo"
                <div style='padding-left: 5%;'>
                  <img src='картинки/not_found.png' style='width:40px;'>
                  <label><h5>По запросу ничего не найдено</h5></label>
                </div>
                ";
              }
              else{
                while($row = $search_genre->fetch_assoc()){
                  $idmedia = $row['idmedia'];
                  $show_img = base64_encode($row['image_cover']);
                  $title = $row['title'];
                  $rating = $row['rating'];
                  $release = date("Y",strtotime($row['release']));
                  $description = $row['description'];
    
                  $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
                  $gcheck=$item_genres->num_rows;
                  
            }
          }
          ?>
            ?>
            <div class="one-item">
            <table>
              <tr>
                <td>
                  <img class="poster" src="картинки/картинка3.jpg">
                </td>
              <td style="overflow: auto;">
                <p><b>Гарри Гончар /19201/</b></p>
                <p><b>Жанры: </b>
                <p><b>Рейтинг: </b>5.5</p>
                <b>Описание:</b><p style="overflow: auto; height: 80px; padding-right: 20px;">Оставляя своё прошлое позади, бегущие от бедности, дискриминации, диктатуры, иммигранты прибывали на остров Эллис. Он был воротами в Соединенные Штаты для миллионов людей. По прибытию их подвергали осмотру и им одобряли или запрещали въезд. Из-за болезни или просто усталости многих размещали в больницы. Остров был своего рода чистилищем в тени Статуи Свободы, где тысячи мужчин, женщин и детей ждали своей судьбы. «Эллис» рассказывает забытую историю этих иммигрантов, которые построили Америку, а также задаётся вопросом о тех, кто в настоящее время находится в поисках тех же возможностей и безопасности в этой стране и других частях мира.<p>
              </td>
              </tr>
            </table>
            
            
            <?
          }
        }
        
        if (isset($show_media)){
          for ($i = 1; $i <= 3; $i++) {
            $query = $con->query("SELECT * FROM media WHERE category_idcategory='$i' IN ('$search_media''$sorting')");
            $checking = $query->num_rows;
            echo"<div style='padding-left: 20px; padding-top: 20px; margin-bottom: 10px;'>";
            if ($i==1){
              if ($show_film){
                echo "<h2><b>Фильмы</b></h2>";
                if ($checking == 0){
                  echo"
                  <div style='padding-left: 5%;'>
                    <img src='картинки/not_found.png' style='width:40px;'>
                    <label><h5>По запросу ничего не найдено</h5></label>
                  </div>
                  ";
                }
              }
            } 
            if ($i==2){
              if ($show_series){
                echo "<h2><b>Сериалы</b></h2>";
                if ($checking == 0){
                  echo"
                  <div style='padding-left: 5%;'>
                    <img src='картинки/not_found.png' style='width:40px;'>
                    <label><h5>По запросу ничего не найдено</h5></label>
                  </div>
                  ";
                }
              }
            }
            if ($i==3){
              if ($show_anime){
                echo "<h2><b>Аниме</b></h2>";
                if ($checking == 0){
                  echo"
                  <div style='padding-left: 5%;'>
                    <img src='картинки/not_found.png' style='width:40px;'>
                    <label><h5>По запросу ничего не найдено</h5></label>
                  </div>
                  ";
                }
              }
            }
            if ($checking != 0){
              while($row = $query->fetch_assoc()){
                  $idmedia = $row['idmedia'];
                  $show_img = base64_encode($row['image_cover']);
                  $title = $row['title'];
                  $rating = $row['rating'];
                  $release = date("Y",strtotime($row['release']));
                  $description = $row['description'];
    
                  $item_genres = $con->query("SELECT * FROM films_genre WHERE media_idmedia='$idmedia'");
                  $gcheck=$item_genres->num_rows;
                  
            }
          }
          ?>
            ?>
            <div class="one-item">
            <table>
              <tr>
                <td>
                  <img class="poster" src="картинки/картинка3.jpg">
                </td>
              <td style="overflow: auto;">
                <p><b>Гарри Гончар /19201/</b></p>
                <p><b>Жанры: </b>
                <p><b>Рейтинг: </b>5.5</p>
                <b>Описание:</b><p style="overflow: auto; height: 80px; padding-right: 20px;">Оставляя своё прошлое позади, бегущие от бедности, дискриминации, диктатуры, иммигранты прибывали на остров Эллис. Он был воротами в Соединенные Штаты для миллионов людей. По прибытию их подвергали осмотру и им одобряли или запрещали въезд. Из-за болезни или просто усталости многих размещали в больницы. Остров был своего рода чистилищем в тени Статуи Свободы, где тысячи мужчин, женщин и детей ждали своей судьбы. «Эллис» рассказывает забытую историю этих иммигрантов, которые построили Америку, а также задаётся вопросом о тех, кто в настоящее время находится в поисках тех же возможностей и безопасности в этой стране и других частях мира.<p>
              </td>
              </tr>
            </table>
            
            
            <?
          }
        }
        
        ?>
        <div style="padding-left: 20px; padding-top: 20px; margin-bottom: 20px;">
          <h3><b>Ищем:</b></h3>
        </div>
        <div style="padding-left: 20px; padding-top: 20px; margin-bottom: 10px;">
          <h2><b>Фильмы</b></h2>
          <div style="padding-left: 5%;">
            <img src='картинки/not_found.png' style="width:40px;">
            <label><h5>По запросу ничего не найдено</h5></label>
          </div>
          <div class="one-item">
            <table>
              <tr>
                <td>
                  <img class="poster" src="картинки/картинка3.jpg">
                </td>
              <td style="overflow: auto;">
                <p><b>Гарри Гончар /19201/</b></p>
                <p><b>Жанры: </b>
                <p><b>Рейтинг: </b>5.5</p>
                <b>Описание:</b><p style="overflow: auto; height: 80px; padding-right: 20px;">Оставляя своё прошлое позади, бегущие от бедности, дискриминации, диктатуры, иммигранты прибывали на остров Эллис. Он был воротами в Соединенные Штаты для миллионов людей. По прибытию их подвергали осмотру и им одобряли или запрещали въезд. Из-за болезни или просто усталости многих размещали в больницы. Остров был своего рода чистилищем в тени Статуи Свободы, где тысячи мужчин, женщин и детей ждали своей судьбы. «Эллис» рассказывает забытую историю этих иммигрантов, которые построили Америку, а также задаётся вопросом о тех, кто в настоящее время находится в поисках тех же возможностей и безопасности в этой стране и других частях мира.<p>
              </td>
              </tr>
            </table>
          <h2><b>Папки</b></h2>
          <div class="folder-div">
            <img src="картинки/folder.png" style="width:40px; margin: 15px;">
            <p class="folder-title">Название</p>
          </div>
        </div>
      </div>
    </main>
</html>